name = "shadcn-ui-mcp-worker"
main = "src/worker.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Optional GitHub token for higher rate limits
GITHUB_TOKEN = ""
